### ISSUE TITLE
Link to this page at npmjs.org gets a 404

### ISSUE THREAD

**Issue by juggledad** [sbrennion/node-red-contrib-play-audiofile#1]
The link to GITHUB at https://www.npmjs.com/package/node-red-contrib-play-audio-file for this node is:
https://github.com/sbrennion/node-red-contrib-play-audio-file
but it should be:
https://github.com/sbrennion/node-red-contrib-play-audiofile

also, why is there a link at the bottom of the Readme.md to a data service site?

**Comment by sbrennion** [comment]
Thanks I changed the link

**Comment by juggledad** [comment]
Can you explain why you have a link to an external site in the readme?

**Comment by edorgeville** [comment]
Still a 404.
